version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:$DB_TAG
    restart: always
    volumes:
      - ~/sqldata/pgsqlvol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=$DB_PHAM
    ports:
      - protocol: tcp
        published: 5432
        target: 5432
    networks:
      - sql

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4:$PG_TAG
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PG_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PG_PASSWORD
    ports:
      - protocol: tcp
        published: 80
        target: 80
    networks:
      - sql

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:$MSDB_TAG
    restart: always
    hostname: mssql
    volumes:
      - ~/sqldata/mssqlvol/data:/var/opt/mssql/data
      - ./files/mssql.conf:/var/opt/mssql/mssql.conf
      - ./flies:/var/opt/mssql/security/ca-certificates
      - ./files/mssql.pem:/etc/ssl/certs/mssql.pem
      - ./files/mssql.key:/etc/ssl/private/mssql.key
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$SA_PASSWORD
      - MSSQL_PID=$MS_PID
      - TZ=$MS_TZ
    cap_add:
      - SYS_PTRACE
    ports:
      - protocol: tcp
        published: 1433
        target: 1433
    networks:
      - sql

volumes:
  mssqlvol:
    name: mssqlvol
  pgsqlvol:
    name: pgsqlvol
  files:
    name: files

networks:
  sql:
    name: sql
