version: '3.1'

services:

  postgres:
    image: postgres:$DB_TAG
    restart: always
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=$DB_PHAM
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:$PG_TAG
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PG_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PG_PASSWORD
    ports:
      - 80:80
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:$MSDB_TAG
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$MSDB_PASSWORD
      - MSSQL_PID=Express
    ports:
      - protocol: tcp
        published: 1433
        target: 1433