version: '3.1'

services:

  postgres:
    image: postgres:$DB_TAG
    restart: always
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=$DB_PHAM
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:$PG_TAG
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PG_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PG_PASSWORD
    ports:
      - 80:80