version: '3.9'

services:

  postgres:
    container_name: postgres
    image: postgres:$DB_TAG
    restart: always
    volumes:
      - ~/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=$DB_PHAM
    ports:
      - protocol: tcp
        published: 5432
        target: 5432

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4:$PG_TAG
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PG_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PG_PASSWORD
    ports:
      - protocol: tcp
        published: 80
        target: 80

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:$MSDB_TAG
    restart: always
    hostname: mssql
    volumes:
      - ~/mssql/data:/var/opt/mssql/data
    user: "0:0"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=$MSDB_PASSWORD
      - MSSQL_PID=$MS_PID
      - PAL_PROGRAM_INFO=1
      - TZ=$MS_TZ
    ports:
      - protocol: tcp
        published: 1433
        target: 1433